#!/usr/bin/env bash
# generate-agent-catalog.sh
# Scans agents/*.md, extracts YAML frontmatter, and writes orchestration/agent-catalog.md.
# Compatible with Bash 3.2 (macOS system shell). No associative arrays, no mapfile, no readarray.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="$REPO_ROOT/agents"
OUTPUT="$REPO_ROOT/orchestration/agent-catalog.md"

# Write catalog header
{
  echo "# Agent Catalog"
  echo ""
  echo "Auto-generated by \`scripts/generate-agent-catalog.sh\`. Do not edit by hand."
  echo ""
  echo "| Agent Name | Description | File Path | Type |"
  echo "| --- | --- | --- | --- |"
} > "$OUTPUT"

# Process each agent file in sorted order
for filepath in $(ls "$AGENTS_DIR"/*.md | sort); do
  name=""
  description=""
  in_frontmatter=0
  frontmatter_done=0
  delim_count=0

  while IFS= read -r line; do
    # Detect frontmatter delimiters
    if [ "$line" = "---" ]; then
      delim_count=$((delim_count + 1))
      if [ "$delim_count" -eq 1 ]; then
        in_frontmatter=1
      elif [ "$delim_count" -eq 2 ]; then
        in_frontmatter=0
        frontmatter_done=1
        break
      fi
      continue
    fi

    # Only parse lines inside frontmatter
    if [ "$in_frontmatter" -eq 1 ]; then
      # Extract name field
      if echo "$line" | grep -q "^name:"; then
        name=$(echo "$line" | sed 's/^name:[[:space:]]*//')
      fi
      # Extract description field (single-line only; these agents all use single-line descriptions)
      if echo "$line" | grep -q "^description:"; then
        description=$(echo "$line" | sed 's/^description:[[:space:]]*//')
      fi
    fi
  done < "$filepath"

  # Skip files without valid frontmatter
  if [ -z "$name" ] || [ "$frontmatter_done" -eq 0 ]; then
    continue
  fi

  # Truncate description to first sentence (up to first period)
  first_sentence=$(echo "$description" | sed 's/\. .*/\./')

  # Classify type: orchestration agents coordinate/spawn other agents;
  # implementation agents perform direct work.
  # Detection: grep description for orchestration-role keywords.
  agent_type="implementation"
  if echo "$description" | grep -qi "orchestrat\|spawn\|decomposit\|recon\|consolidat\|Scribe\|gather\|review specialist.*team\|parallel research"; then
    agent_type="orchestration"
  fi
  # Scout, Surveyor, Architect, Pantry, Big Head, Technical Writer are orchestration roles.
  # Nitpicker is implementation (runs as one of 4 parallel reviewers, not a coordinator itself).
  # Pest Control is implementation (auditor, not a spawner).
  # Override by name for precision:
  case "$name" in
    ant-farm-scout-organizer|ant-farm-surveyor|ant-farm-architect|ant-farm-pantry-impl|ant-farm-big-head|ant-farm-technical-writer|ant-farm-forager)
      agent_type="orchestration"
      ;;
    ant-farm-nitpicker|ant-farm-pest-control)
      agent_type="implementation"
      ;;
  esac

  # Relative file path from repo root
  rel_path="agents/$(basename "$filepath")"

  # Append row — escape any pipe characters in description
  safe_desc=$(echo "$first_sentence" | sed 's/|/\\|/g')
  printf "| %s | %s | %s | %s |\n" "$name" "$safe_desc" "$rel_path" "$agent_type" >> "$OUTPUT"
done

echo "Wrote $OUTPUT"
