#!/usr/bin/env bash
# generate-agent-catalog.sh
# Scans agents/*.md, extracts YAML frontmatter, and writes orchestration/agent-catalog.md.
# Compatible with Bash 3.2 (macOS system shell). No associative arrays, no mapfile, no readarray.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="$REPO_ROOT/agents"
OUTPUT="$REPO_ROOT/orchestration/agent-catalog.md"

# Write catalog header
{
  echo "# Agent Catalog"
  echo ""
  echo "Auto-generated by \`scripts/generate-agent-catalog.sh\`. Do not edit by hand."
  echo ""
  echo "| Agent Name | Description | File Path | Type |"
  echo "| --- | --- | --- | --- |"
} > "$OUTPUT"

# Process each agent file in sorted order
shopt -s nullglob
for filepath in "$AGENTS_DIR"/*.md; do
  name=""
  description=""
  in_frontmatter=0
  frontmatter_done=0
  delim_count=0

  while IFS= read -r line; do
    # Detect frontmatter delimiters
    if [ "$line" = "---" ]; then
      delim_count=$((delim_count + 1))
      if [ "$delim_count" -eq 1 ]; then
        in_frontmatter=1
      elif [ "$delim_count" -eq 2 ]; then
        in_frontmatter=0
        frontmatter_done=1
        break
      fi
      continue
    fi

    # Only parse lines inside frontmatter
    if [ "$in_frontmatter" -eq 1 ]; then
      # Extract name field
      if echo "$line" | grep -q "^name:"; then
        name=$(echo "$line" | sed "s/^name:[[:space:]]*//; s/^['\"]//; s/['\"]$//")
      fi
      # Extract description field (single-line only; these agents all use single-line descriptions)
      if echo "$line" | grep -q "^description:"; then
        description=$(echo "$line" | sed 's/^description:[[:space:]]*//')
      fi
    fi
  done < "$filepath"

  # Skip files without valid frontmatter
  if [ -z "$name" ] || [ "$frontmatter_done" -eq 0 ]; then
    continue
  fi

  # Truncate description to first sentence.
  # Match period + space + uppercase letter to identify sentence boundaries,
  # avoiding false matches on abbreviations like "e.g." or "i.e."
  first_sentence=$(echo "$description" | sed 's/\. [A-Z].*/\./')

  # Classify type: orchestration agents coordinate/spawn other agents;
  # implementation agents perform direct work.
  # Detection: grep description (case-insensitive) for orchestration-role keywords:
  #   orchestrat   — matches "orchestration", "orchestrator"
  #   spawn        — agents that launch sub-agents
  #   decomposit   — task decomposition / breakdown roles
  #   recon        — reconnaissance / scouting roles
  #   consolidat   — agents that merge/consolidate results
  #   scribe       — session scribes / documentation writers
  #   gather       — information-gathering agents
  #   review specialist.*team — agents that assemble review teams
  #   parallel research       — agents coordinating parallel research
  agent_type="implementation"
  if echo "$description" | grep -qi "orchestrat\|spawn\|decomposit\|recon\|consolidat\|scribe\|gather\|review specialist.*team\|parallel research"; then
    agent_type="orchestration"
  fi
  # Scout (recon-planner), Spec Writer (spec-writer), Task Decomposer (task-decomposer),
  # Pantry (prompt-composer), Review Consolidator (review-consolidator), Session Scribe (session-scribe),
  # and Researcher (researcher) are orchestration roles.
  # Reviewer specialists are review agents (run as parallel reviewers, not coordinators).
  # Checkpoint Auditor is review (auditor, not a spawner).
  # Override by name for precision:
  case "$name" in
    ant-farm-recon-planner|ant-farm-spec-writer|ant-farm-task-decomposer|ant-farm-prompt-composer|ant-farm-review-consolidator|ant-farm-session-scribe|ant-farm-researcher)
      agent_type="orchestration"
      ;;
    ant-farm-reviewer-clarity|ant-farm-reviewer-edge-cases|ant-farm-reviewer-correctness|ant-farm-reviewer-drift|ant-farm-checkpoint-auditor)
      agent_type="review"
      ;;
  esac

  # Relative file path from repo root
  rel_path="agents/$(basename "$filepath")"

  # Append row — escape any pipe characters in description
  safe_desc=$(echo "$first_sentence" | sed 's/|/\\|/g')
  printf "| %s | %s | %s | %s |\n" "$name" "$safe_desc" "$rel_path" "$agent_type" >> "$OUTPUT"
done
shopt -u nullglob

echo "Wrote $OUTPUT"
